name: Test and Merge

on:
  push:
    branches:
      - master
      - 'feature/*' # Esto incluye cualquier rama que empiece con "feature/"
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
